<?php
    session_start();
    if(isset($_SESSION['mySession'])){
        unset($_SESSION['mySession']);
        session_destroy();
        header("Location:index.php");
    }else{
        header("Location:index.php");
    }
?>